### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by 3laws** [dracula/tumblr#1]
Given the new personalization/accessibility setting [Color Palette ](https://help.tumblr.com/accessibility/#h_01HRPP1JMTYPRQMHCD8TP2Y1SS). Default Tumbr behavior is not accounted for in this CSS.

![image](https://github.com/dracula/tumblr/assets/4267075/aa960f01-da36-4cc6-b9cd-ee2c01525daf)
Applying this with Stylus leads to only the Search Bar being changed while the site still respects the selected Color Palette.

**Comment by D-u-c-k-s-e-l** [comment]
In the screenshot you sent, all the correct colors seem to be in place. (the grays in the backgrounds and the purple accent color)

I don't use stylus myself for this theme and have been meaning to port it, but I thought I'd try to recreate the issue.

I pressed the `Write style for` button, and pasted the file. It seemed to give a similar screenshot to yours. I then opened tumblr settings to try changing the theme. On the settings page, dracula wasn't applying.

My issue was in stylus. Within the style editor, there is a box that says `URLs starting with`. This was set to `https://www.tumblr.com/dashboard` rather than `https://www.tumblr.com`.

I hope this helps.

**Comment by 3laws** [comment]
> but I thought I'd try to recreate the issue.


Appreciate it a lot! But I don't think you see what I'm seeing cuz I can eyedrop on those grays and they're not at all any of the tones either in the screenshot provided by this repo nor the ones [in here.](https://draculatheme.com/contribute)

![image](https://github.com/dracula/tumblr/assets/4267075/07c3b4a7-be6e-4b83-a44a-911057808cab)


What I'm getting at, either the instructions are incomplete/obtuse or it doesn't work at all with Stylus (nothing wrong with that, just a clear documentation touch up would help others) and we could find a way to accommodate for that accordingly.
